version: '3.9'
services:
  # node-server:
  #   container_name: node
  #   build: . 
  #   ports:
  #     - "3000:3000" # out: in
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  pg_data:
